# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
# info: change version to update pants
pants_version = "2.14.0.dev0"
colors = true
use_deprecated_pex_binary_run_semantics = true


backend_packages.add = [
  'pants.backend.python',
  'pants.backend.python.lint.docformatter',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  'pants.backend.python.typecheck.mypy',
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[tailor]
ignore_adding_targets = ['django:manage']

[python]
interpreter_constraints = ["CPython==3.8.*"]
lockfile_generator = "pex"
enable_resolves = true
default_resolve = "default"

[python-infer]
#inits = true
init_files = "always"
string_imports = true
string_imports_min_dots = 0

[python.resolves]
default = "lockfiles/python/default"


[pytest]
lockfile = "lockfiles/python/tools/pytest"
version = "pytest>=7.1.2,<7.2"
extra_requirements.add = [
  "pytest-django==4.5.2",
  "pytest-icdiff==0.5",
  "mixer==7.2.1"
]
config_discovery = true

[test]        
#debug = true


[anonymous-telemetry]
# do not send telemetry data
enabled = false
